import {Model} from '../src'

describe('Model', () => {
	const instance = new Model()
	it('instance should be an instanceof Model', () => expect(instance).toBeInstanceOf(Model))
	it('should have a property id', () => expect('id' in instance).toBeTruthy())
	it('should have a property data', () => expect(instance.data).toBeDefined())
	it('should have a property append', () => expect(instance.append).toBeDefined())
	it('should have a method get()', () => expect(typeof instance.get).toBe('function'))
	it('should have a method find()', () => expect(typeof instance.find).toBe('function'))
	it('should have a method findKey()', () => expect(typeof instance.findKey).toBe('function'))
	it('should have a method first()', () => expect(typeof instance.first).toBe('function'))
	it('should have a method last()', () => expect(typeof instance.last).toBe('function'))
	it('should have a method set()', () => expect(typeof instance.set).toBe('function'))
	it('should have a method has()', () => expect(typeof instance.has).toBe('function'))
	it('should have a method keys()', () => expect(typeof instance.keys).toBe('function'))
	it('should have a method count()', () => expect(typeof instance.count).toBe('function'))
	it('should have a method empty()', () => expect(typeof instance.empty).toBe('function'))
	it('should have a method coalesce()', () => expect(typeof instance.coalesce).toBe('function'))
	it('should have a method insert()', () => expect(typeof instance.insert).toBe('function'))
	it('should have a method push()', () => expect(typeof instance.push).toBe('function'))
	it('should have a method pull()', () => expect(typeof instance.pull).toBe('function'))
	it('should have a method patch()', () => expect(typeof instance.patch).toBe('function'))
	it('should have a method patch()', () => expect(typeof instance.patch).toBe('function'))
	it('should have a method increment()', () => expect(typeof instance.increment).toBe('function'))
	it('should have a method decrement()', () => expect(typeof instance.decrement).toBe('function'))
	it('should have a method ensureExists()', () => expect(typeof instance.ensureExists).toBe('function'))
	it('should have a method remove()', () => expect(typeof instance.remove).toBe('function'))
	it('should have a method validate()', () => expect(typeof instance.validate).toBe('function'))
})
